root: true
env:
  browser: true
  es2022: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:vue/vue3-recommended"
  - "@vue/typescript/recommended"
  - "prettier"
overrides:
  - files:
      - "*.config.{js,ts}"
    extends:
      - "plugin:@typescript-eslint/recommended-requiring-type-checking"
parserOptions:
  sourceType: module
  project: "./tsconfig.json"
ignorePatterns:
  - vite.config.ts
plugins:
  - vue
  - "@typescript-eslint"
  - prettier
rules:
  "vue/component-name-in-template-casing":
    - "error"
    - "PascalCase"
