env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - "@vue/typescript/recommended"
  - prettier
overrides:
  - files:
      - "*.config.{ts,js}"
    extends:
      - "@typescript-eslint/disable-type-checked"
parser: "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
  extraFileExtensions:
    - ".vue"
plugins:
  - vue
  - "@typescript-eslint"
  - prettier
rules:
  vue/component-name-in-template-casing:
    - "error"
    - "PascalCase"
